### ISSUE TITLE
json config files?

### ISSUE THREAD

**Issue by jifilis** [homen3/cryptotrader#1]
Hi,
Any json sample to config json files?

poloniex.json
bittrex.json
kraken.json

No sample files in any folder..

Tks!

**Comment by MartinSeeler** [comment]
I was also looking for the file format. Sadly not provided...

**Comment by homen3** [comment]
examples config files are now included. There aren't examples using auth to exchanges right now, but you can see example on specified api lib that i'm using:
- poloniex https://github.com/rferro/plnx
- bittrex https://github.com/5an1ty/kraken-api
- kraken https://github.com/n0mad01/node.bittrex.api

**Comment by MartinSeeler** [comment]
Thx!
